"use client";
import { Poppins } from "@next/font/google";
import "./globals.scss";
import Layout from "../components/Layout/layout";
import AuthLayout from "../components/AuthLayout/AuthLayout";

const poppins = Poppins({
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const isLoggedIn = false;  // Replace this with your actual authentication logic

  return (
    <html lang="en">
      <body className={`overflow-hidden ${poppins.className}`}>
        {isLoggedIn ? (
          <Layout data={children} />
        ) : (
          <AuthLayout data={children} />
        )}
      </body>
    </html>
  );
}
